FROM node:22-alpine 
WORKDIR /app/redirect-service

# Copy package.json and package-lock.json cleanly
COPY package.json package-lock.json ./

# Use a clean install if a lockfile exists, or standard install
RUN npm install

EXPOSE 10027

COPY . .