name: nexus-stream-development

services:
  core-service:
    build:
      context: ./services/core-service
      dockerfile: dockerfile
      target: development
    ports:
      - "3000:10000"
    depends_on:
      redis-cache:
        condition: service_healthy
      minio:
        condition: service_started
      db-service:
        condition: service_healthy
    volumes: 
      - ./services/core-service:/builder/core-service
    env_file:
      - ./services/core-service/.env.dummy
    networks:
      - nexus-network 

  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: DockerFile
    ports:
      - "3050:3050"
    env_file:
      - ./services/gateway-service/.env.dummy
    depends_on:
      redis-cache:
        condition: service_healthy
    volumes: 
      - ./services/gateway-service:/app/gateway-service
      - /app/gateway-service/node_modules
    command: npm run test
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3050/"]
      interval: 5s
      timeout: 3s
      retries: 3
  cloudfare-worker:
    build:
      context: ./services/cloudfare-worker
      dockerfile: DockerFile
    ports:
      - "8787:8787"
    volumes:
      - ./services/cloudfare-worker:/app/cloudfare-worker
      - /app/node_modules
    networks:
      - nexus-network
  cloudfare-worker-2:
    build:
      context: ./services/cloudfare-worker-2
      dockerfile: DockerFile
    ports:
      - "8788:8788"
    volumes:
      - ./services/cloudfare-worker-2:/app/cloudfare-worker-2
      - /app/node_modules
    networks:
      - nexus-network
  web-client:
    build: 
      context: ./services/web-client
      dockerfile: DockerFile
    depends_on:
      gateway-service:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - ./services/web-client/.env.dummy
    volumes:
      - ./services/web-client:/app/web-client
      - /app/web-client/node_modules
    networks:
      - nexus-network

  nginx-iac:
    build:
      context: ./Infrastructure/nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80" 
    volumes:
      - ./Infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nexus-network

  redis-cache:
    build: 
      context: ./Infrastructure/redis-cache
      dockerfile: dockerfile
    volumes:
      - redis_data:/data
      - ./Infrastructure/redis-cache/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_SERVER_URL: "http://localhost:9000"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - nexus-network

  video-processor:
    build:
      context: ./services/video-processor
      dockerfile: DockerFile
    ports:
      - "4781:4781"
    volumes:
      - ./services/video-processor/:/app/video-processor/
      - /app/video-processor/node_modules
      - /app/video-processor/temp-storage
    env_file:
      - ./services/video-processor/.env.dummy
    networks:
      - nexus-network
    depends_on:
      redis-cache:
        condition: service_healthy
    command: npm run dev

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 admin password123) do echo 'Waiting for MinIO...'; sleep 1; done;
      /usr/bin/mc mb myminio/nexustream --ignore-existing;
      /usr/bin/mc anonymous set private myminio/nexustream;
      exit 0;
      "
    networks:
      - nexus-network

  db-service:
    image: postgres:14-alpine3.24
    container_name: db-service
    ports:
      - "10024:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=supradb 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready is the built-in postgres tool to check if the DB is accepting connections
      test: ["CMD-SHELL", "pg_isready -U postgres -d supradb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nexus-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "10025:80"
    networks:
      - nexus-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db-service:
        # Ensures pgAdmin won't start until Postgres passes its healthcheck
        condition: service_healthy
    healthcheck:
      # Pings the built-in pgAdmin health endpoint. Fails (exit 1) if it doesn't get a 200 OK.
      test: ["CMD-SHELL", "wget -q --spider http://localhost/misc/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  redirect-service:
    build:
      context: ./services/redirect-service
      dockerfile: dockerfile
    ports:
      - "10027:10027"
    volumes:
      - ./services/redirect-service/:/app/redirect-service/
      - /app/redirect-service/node_modules
    env_file:
      - ./services/redirect-service/.env.dummy
    networks:
      - nexus-network
    command: npm run dev

    


networks:
  nexus-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data:
  kafka_data:
  pgadmin-data: