server {
    listen 80;
    server_name localhost 10.154.162.64;
    client_max_body_size 500M;

    # Frontend / Web Client
    location / {
        proxy_pass http://web-client:4000;
        
        # --- CRITICAL FOR WEBSOCKETS ---
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Help Vite identify the host
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    # API Gateway (Express App)
    location /apiV2/ { 
        proxy_pass http://gateway-service:3050; 
        # --- CRITICAL FOR WEBSOCKETS ---
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Ensure cookies pass seamlessly through Nginx
        proxy_pass_header Set-Cookie;
    }

    # Core Service (Spring Boot)
    location /apiV1/ { 
        proxy_pass http://core-service:10000/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Ensure cookies pass seamlessly through Nginx
        proxy_pass_header Set-Cookie;
    }
    location /minio/ {
    rewrite ^/minio/(.*)$ /$1 break;
    proxy_pass http://minio:9000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    # Disable buffering for large file uploads (like videos)
    proxy_buffering off;
    client_max_body_size 0; # Prevents Nginx "413 Request Entity Too Large" errors
}
    location /minio/ui/ {
        proxy_pass http://minio:9001/;
    }
}