spring.application.name=core-service
server.port=${SERVER_PORT:8080}

# DevTools Configuration
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms
spring.devtools.livereload.enabled=${SPRING_DEVTOOLS_LIVERELOAD_ENABLED:false}
spring.devtools.restart.enabled=${SPRING_DEVTOOLS_RESTART_ENABLED:false}

# Database (MySQL)
spring.datasource.url=jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:springdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

# Security
JWT_KEY=${JWT_KEY:supersecretkeythatisverylongandsecure12345!}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}

# Redis Cache
redis.auth.host=${REDIS_HOST:localhost}
redis.auth.port=${REDIS_PORT:6379}
redis.auth.password=${REDIS_PASSWORD:1234}

redis.queue.host=${REDIS_HOST:localhost}
redis.queue.port=${REDIS_PORT:6379}
redis.queue.password=${REDIS_PASSWORD:1234}

logging.level.org.springframework.data.redis=${REDIS_LOG_LEVEL:INFO}

# Proxy/Load Balancer Headers
server.forward-headers-strategy=framework

# AWS S3 / MinIO
aws.s3.endpoint=${S3_ENDPOINT:http://localhost:9000}
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.access-key=${AWS_ACCESS_KEY:username}
aws.s3.secret-key=${AWS_SECRET_KEY:password}
aws.s3.bucket=${AWS_S3_BUCKET:bucketname}
aws.s3.path-style-access=${AWS_S3_PATH_STYLE:false}

# AWS S3 / MinIO
aws.s3.endpoint_2=${S3_ENDPOINT:http://localhost:9000}
aws.s3.region_2=${AWS_REGION:us-east-1}
aws.s3.access-key_2=${AWS_ACCESS_KEY:username}
aws.s3.secret-key_2=${AWS_SECRET_KEY:password}
aws.s3.bucket_2=${AWS_S3_BUCKET:bucketname}
aws.s3.path-style-access_2=${AWS_S3_PATH_STYLE:false}

S3_BASE_URL=${S3_BASE_URL}

# Kafka Producer & Consumer
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Kafka Deserializer Properties
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=${KAFKA_DEFAULT_TYPE}
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=${KAFKA_TRUSTED_PACKAGES}

# Cache tokens for 1 minutes
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=1m,maximumSize=200

# Using : to provide a default value after the variable
topic.video.processed=${TOPIC_VIDEO_PROCESSED:video-processed-default}
topic.notification=${TOPIC_NOTIFICATION:notification-default}
topic.video.uploaded=${TOPIC_VIDEO_UPLOADED:video-uploaded-default}
topic.video.processing.failed=${TOPIC_VIDEO_PROCESSING_FAILED:video-uploaded-default}

SPRING_ENV=${SPRING_ENV}